language: go

go:
  - 1.10.x
  - 1.11.x
  - 1.12.x
  - tip
  - master

go_import_path: stash.kopano.io/kgol/kcc-go

matrix:
  allow_failures:
    - go: tip master
  fast_finish: true

before_install:
  - curl https://raw.githubusercontent.com/golang/dep/master/install.sh | sh
  - export PATH="$GOPATH/bin:$PATH"

install:
  - dep ensure

script: go install -v ./...
