/*
 * Copyright 2018 Kopano and its licensors
 *
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU Affero General Public License, version 3,
 * as published by the Free Software Foundation.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
 * GNU Affero General Public License for more details.
 *
 * You should have received a copy of the GNU Affero General Public License
 * along with this program.  If not, see <http://www.gnu.org/licenses/>.
 *
 */

package kcc

// Property value types as defined in mapi4linux/include/mapitags.h and
// mapi4linux/include/mapidefs.h. This defines all property types
// independently from kcc-go support.
const (
	MV_FLAG = 0x1000

	PT_UNSPECIFIED uint64 = 0x0000
	PT_NULL        uint64 = 0x0001
	PT_SHORT       uint64 = 0x0002
	PT_LONG        uint64 = 0x0003
	PT_FLOAT       uint64 = 0x0004
	PT_DOUBLE      uint64 = 0x0005
	PT_CURRENCY    uint64 = 0x0006
	PT_APPTIME     uint64 = 0x0007
	PT_ERROR       uint64 = 0x000A
	PT_BOOLEAN     uint64 = 0x000B
	PT_OBJECT      uint64 = 0x000D
	PT_LONGLONG    uint64 = 0x0014
	PT_STRING8     uint64 = 0x001E
	PT_UNICODE     uint64 = 0x001F
	PT_SYSTIME     uint64 = 0x0040
	PT_CLSID       uint64 = 0x0048
	PT_BINARY      uint64 = 0x0102

	PT_MV_SHORT    = (MV_FLAG | PT_SHORT)
	PT_MV_LONG     = (MV_FLAG | PT_LONG)
	PT_MV_FLOAT    = (MV_FLAG | PT_FLOAT)
	PT_MV_DOUBLE   = (MV_FLAG | PT_DOUBLE)
	PT_MV_CURRENCY = (MV_FLAG | PT_CURRENCY)
	PT_MV_APPTIME  = (MV_FLAG | PT_APPTIME)
	PT_MV_SYSTIME  = (MV_FLAG | PT_SYSTIME)
	PT_MV_STRING8  = (MV_FLAG | PT_STRING8)
	PT_MV_BINARY   = (MV_FLAG | PT_BINARY)
	PT_MV_UNICODE  = (MV_FLAG | PT_UNICODE)
	PT_MV_CLSID    = (MV_FLAG | PT_CLSID)
	PT_MV_LONGLONG = (MV_FLAG | PT_LONGLONG)

	PT_TSTRING    = PT_UNICODE
	PT_MV_TSTRING = (MV_FLAG | PT_UNICODE)

	PROP_TYPE_MASK uint64 = 0x0000FFFF
)

func propTag(propType, propID uint64) uint64 {
	return (propID << 16) | propType
}

// Property names as defined in mapi4linux/include/mapitags.h and
// mapi4linux/include/mapidefs.h. This defines all property names
// independently from kcc-go support.
var (
	PR_7BIT_DISPLAY_NAME            = propTag(PT_STRING8, 0x39FF)
	PR_ACCOUNT                      = propTag(PT_TSTRING, 0x3A00)
	PR_ACCOUNT_W                    = propTag(PT_UNICODE, 0x3A00)
	PR_ACCOUNT_A                    = propTag(PT_STRING8, 0x3A00)
	PR_ALTERNATE_RECIPIENT          = propTag(PT_BINARY, 0x3A01)
	PR_CALLBACK_TELEPHONE_NUMBER    = propTag(PT_TSTRING, 0x3A02)
	PR_CALLBACK_TELEPHONE_NUMBER_W  = propTag(PT_UNICODE, 0x3A02)
	PR_CALLBACK_TELEPHONE_NUMBER_A  = propTag(PT_STRING8, 0x3A02)
	PR_CONVERSION_PROHIBITED        = propTag(PT_BOOLEAN, 0x3A03)
	PR_DISCLOSE_RECIPIENTS          = propTag(PT_BOOLEAN, 0x3A04)
	PR_GENERATION                   = propTag(PT_TSTRING, 0x3A05)
	PR_GENERATION_W                 = propTag(PT_UNICODE, 0x3A05)
	PR_GENERATION_A                 = propTag(PT_STRING8, 0x3A05)
	PR_GIVEN_NAME                   = propTag(PT_TSTRING, 0x3A06)
	PR_GIVEN_NAME_W                 = propTag(PT_UNICODE, 0x3A06)
	PR_GIVEN_NAME_A                 = propTag(PT_STRING8, 0x3A06)
	PR_GOVERNMENT_ID_NUMBER         = propTag(PT_TSTRING, 0x3A07)
	PR_GOVERNMENT_ID_NUMBER_W       = propTag(PT_UNICODE, 0x3A07)
	PR_GOVERNMENT_ID_NUMBER_A       = propTag(PT_STRING8, 0x3A07)
	PR_BUSINESS_TELEPHONE_NUMBER    = propTag(PT_TSTRING, 0x3A08)
	PR_BUSINESS_TELEPHONE_NUMBER_W  = propTag(PT_UNICODE, 0x3A08)
	PR_BUSINESS_TELEPHONE_NUMBER_A  = propTag(PT_STRING8, 0x3A08)
	PR_OFFICE_TELEPHONE_NUMBER      = PR_BUSINESS_TELEPHONE_NUMBER
	PR_OFFICE_TELEPHONE_NUMBER_W    = PR_BUSINESS_TELEPHONE_NUMBER_W
	PR_OFFICE_TELEPHONE_NUMBER_A    = PR_BUSINESS_TELEPHONE_NUMBER_A
	PR_HOME_TELEPHONE_NUMBER        = propTag(PT_TSTRING, 0x3A09)
	PR_HOME_TELEPHONE_NUMBER_W      = propTag(PT_UNICODE, 0x3A09)
	PR_HOME_TELEPHONE_NUMBER_A      = propTag(PT_STRING8, 0x3A09)
	PR_INITIALS                     = propTag(PT_TSTRING, 0x3A0A)
	PR_INITIALS_W                   = propTag(PT_UNICODE, 0x3A0A)
	PR_INITIALS_A                   = propTag(PT_STRING8, 0x3A0A)
	PR_KEYWORD                      = propTag(PT_TSTRING, 0x3A0B)
	PR_KEYWORD_W                    = propTag(PT_UNICODE, 0x3A0B)
	PR_KEYWORD_A                    = propTag(PT_STRING8, 0x3A0B)
	PR_LANGUAGE                     = propTag(PT_TSTRING, 0x3A0C)
	PR_LANGUAGE_W                   = propTag(PT_UNICODE, 0x3A0C)
	PR_LANGUAGE_A                   = propTag(PT_STRING8, 0x3A0C)
	PR_LOCATION                     = propTag(PT_TSTRING, 0x3A0D)
	PR_LOCATION_W                   = propTag(PT_UNICODE, 0x3A0D)
	PR_LOCATION_A                   = propTag(PT_STRING8, 0x3A0D)
	PR_MAIL_PERMISSION              = propTag(PT_BOOLEAN, 0x3A0E)
	PR_MHS_COMMON_NAME              = propTag(PT_TSTRING, 0x3A0F)
	PR_MHS_COMMON_NAME_W            = propTag(PT_UNICODE, 0x3A0F)
	PR_MHS_COMMON_NAME_A            = propTag(PT_STRING8, 0x3A0F)
	PR_ORGANIZATIONAL_ID_NUMBER     = propTag(PT_TSTRING, 0x3A10)
	PR_ORGANIZATIONAL_ID_NUMBER_W   = propTag(PT_UNICODE, 0x3A10)
	PR_ORGANIZATIONAL_ID_NUMBER_A   = propTag(PT_STRING8, 0x3A10)
	PR_SURNAME                      = propTag(PT_TSTRING, 0x3A11)
	PR_SURNAME_W                    = propTag(PT_UNICODE, 0x3A11)
	PR_SURNAME_A                    = propTag(PT_STRING8, 0x3A11)
	PR_ORIGINAL_ENTRYID             = propTag(PT_BINARY, 0x3A12)
	PR_ORIGINAL_DISPLAY_NAME        = propTag(PT_TSTRING, 0x3A13)
	PR_ORIGINAL_DISPLAY_NAME_W      = propTag(PT_UNICODE, 0x3A13)
	PR_ORIGINAL_DISPLAY_NAME_A      = propTag(PT_STRING8, 0x3A13)
	PR_ORIGINAL_SEARCH_KEY          = propTag(PT_BINARY, 0x3A14)
	PR_POSTAL_ADDRESS               = propTag(PT_TSTRING, 0x3A15)
	PR_POSTAL_ADDRESS_W             = propTag(PT_UNICODE, 0x3A15)
	PR_POSTAL_ADDRESS_A             = propTag(PT_STRING8, 0x3A15)
	PR_COMPANY_NAME                 = propTag(PT_TSTRING, 0x3A16)
	PR_COMPANY_NAME_W               = propTag(PT_UNICODE, 0x3A16)
	PR_COMPANY_NAME_A               = propTag(PT_STRING8, 0x3A16)
	PR_TITLE                        = propTag(PT_TSTRING, 0x3A17)
	PR_TITLE_W                      = propTag(PT_UNICODE, 0x3A17)
	PR_TITLE_A                      = propTag(PT_STRING8, 0x3A17)
	PR_DEPARTMENT_NAME              = propTag(PT_TSTRING, 0x3A18)
	PR_DEPARTMENT_NAME_W            = propTag(PT_UNICODE, 0x3A18)
	PR_DEPARTMENT_NAME_A            = propTag(PT_STRING8, 0x3A18)
	PR_OFFICE_LOCATION              = propTag(PT_TSTRING, 0x3A19)
	PR_OFFICE_LOCATION_W            = propTag(PT_UNICODE, 0x3A19)
	PR_OFFICE_LOCATION_A            = propTag(PT_STRING8, 0x3A19)
	PR_PRIMARY_TELEPHONE_NUMBER     = propTag(PT_TSTRING, 0x3A1A)
	PR_PRIMARY_TELEPHONE_NUMBER_W   = propTag(PT_UNICODE, 0x3A1A)
	PR_PRIMARY_TELEPHONE_NUMBER_A   = propTag(PT_STRING8, 0x3A1A)
	PR_BUSINESS2_TELEPHONE_NUMBER   = propTag(PT_TSTRING, 0x3A1B)
	PR_BUSINESS2_TELEPHONE_NUMBER_W = propTag(PT_UNICODE, 0x3A1B)
	PR_BUSINESS2_TELEPHONE_NUMBER_A = propTag(PT_STRING8, 0x3A1B)
	PR_OFFICE2_TELEPHONE_NUMBER     = PR_BUSINESS2_TELEPHONE_NUMBER
	PR_OFFICE2_TELEPHONE_NUMBER_W   = PR_BUSINESS2_TELEPHONE_NUMBER_W
	PR_OFFICE2_TELEPHONE_NUMBER_A   = PR_BUSINESS2_TELEPHONE_NUMBER_A
	PR_MOBILE_TELEPHONE_NUMBER      = propTag(PT_TSTRING, 0x3A1C)
	PR_MOBILE_TELEPHONE_NUMBER_W    = propTag(PT_UNICODE, 0x3A1C)
	PR_MOBILE_TELEPHONE_NUMBER_A    = propTag(PT_STRING8, 0x3A1C)
	PR_CELLULAR_TELEPHONE_NUMBER    = PR_MOBILE_TELEPHONE_NUMBER
	PR_CELLULAR_TELEPHONE_NUMBER_W  = PR_MOBILE_TELEPHONE_NUMBER_W
	PR_CELLULAR_TELEPHONE_NUMBER_A  = PR_MOBILE_TELEPHONE_NUMBER_A
	PR_RADIO_TELEPHONE_NUMBER       = propTag(PT_TSTRING, 0x3A1D)
	PR_RADIO_TELEPHONE_NUMBER_W     = propTag(PT_UNICODE, 0x3A1D)
	PR_RADIO_TELEPHONE_NUMBER_A     = propTag(PT_STRING8, 0x3A1D)
	PR_CAR_TELEPHONE_NUMBER         = propTag(PT_TSTRING, 0x3A1E)
	PR_CAR_TELEPHONE_NUMBER_W       = propTag(PT_UNICODE, 0x3A1E)
	PR_CAR_TELEPHONE_NUMBER_A       = propTag(PT_STRING8, 0x3A1E)
	PR_OTHER_TELEPHONE_NUMBER       = propTag(PT_TSTRING, 0x3A1F)
	PR_OTHER_TELEPHONE_NUMBER_W     = propTag(PT_UNICODE, 0x3A1F)
	PR_OTHER_TELEPHONE_NUMBER_A     = propTag(PT_STRING8, 0x3A1F)
	PR_TRANSMITABLE_DISPLAY_NAME    = propTag(PT_TSTRING, 0x3A20)
	PR_TRANSMITABLE_DISPLAY_NAME_W  = propTag(PT_UNICODE, 0x3A20)
	PR_TRANSMITABLE_DISPLAY_NAME_A  = propTag(PT_STRING8, 0x3A20)
	PR_PAGER_TELEPHONE_NUMBER       = propTag(PT_TSTRING, 0x3A21)
	PR_PAGER_TELEPHONE_NUMBER_W     = propTag(PT_UNICODE, 0x3A21)
	PR_PAGER_TELEPHONE_NUMBER_A     = propTag(PT_STRING8, 0x3A21)
	PR_BEEPER_TELEPHONE_NUMBER      = PR_PAGER_TELEPHONE_NUMBER
	PR_BEEPER_TELEPHONE_NUMBER_W    = PR_PAGER_TELEPHONE_NUMBER_W
	PR_BEEPER_TELEPHONE_NUMBER_A    = PR_PAGER_TELEPHONE_NUMBER_A
	PR_USER_CERTIFICATE             = propTag(PT_BINARY, 0x3A22)
	PR_PRIMARY_FAX_NUMBER           = propTag(PT_TSTRING, 0x3A23)
	PR_PRIMARY_FAX_NUMBER_W         = propTag(PT_UNICODE, 0x3A23)
	PR_PRIMARY_FAX_NUMBER_A         = propTag(PT_STRING8, 0x3A23)
	PR_BUSINESS_FAX_NUMBER          = propTag(PT_TSTRING, 0x3A24)
	PR_BUSINESS_FAX_NUMBER_W        = propTag(PT_UNICODE, 0x3A24)
	PR_BUSINESS_FAX_NUMBER_A        = propTag(PT_STRING8, 0x3A24)
	PR_HOME_FAX_NUMBER              = propTag(PT_TSTRING, 0x3A25)
	PR_HOME_FAX_NUMBER_W            = propTag(PT_UNICODE, 0x3A25)
	PR_HOME_FAX_NUMBER_A            = propTag(PT_STRING8, 0x3A25)
	PR_COUNTRY                      = propTag(PT_TSTRING, 0x3A26)
	PR_COUNTRY_W                    = propTag(PT_UNICODE, 0x3A26)
	PR_COUNTRY_A                    = propTag(PT_STRING8, 0x3A26)
	PR_BUSINESS_ADDRESS_COUNTRY     = PR_COUNTRY
	PR_BUSINESS_ADDRESS_COUNTRY_W   = PR_COUNTRY_W
	PR_BUSINESS_ADDRESS_COUNTRY_A   = PR_COUNTRY_A

	PR_LOCALITY                = propTag(PT_TSTRING, 0x3A27)
	PR_LOCALITY_W              = propTag(PT_UNICODE, 0x3A27)
	PR_LOCALITY_A              = propTag(PT_STRING8, 0x3A27)
	PR_BUSINESS_ADDRESS_CITY   = PR_LOCALITY
	PR_BUSINESS_ADDRESS_CITY_W = PR_LOCALITY_W
	PR_BUSINESS_ADDRESS_CITY_A = PR_LOCALITY_A

	PR_STATE_OR_PROVINCE                    = propTag(PT_TSTRING, 0x3A28)
	PR_STATE_OR_PROVINCE_W                  = propTag(PT_UNICODE, 0x3A28)
	PR_STATE_OR_PROVINCE_A                  = propTag(PT_STRING8, 0x3A28)
	PR_BUSINESS_ADDRESS_STATE_OR_PROVINCE   = PR_STATE_OR_PROVINCE
	PR_BUSINESS_ADDRESS_STATE_OR_PROVINCE_W = PR_STATE_OR_PROVINCE_W
	PR_BUSINESS_ADDRESS_STATE_OR_PROVINCE_A = PR_STATE_OR_PROVINCE_A

	PR_STREET_ADDRESS            = propTag(PT_TSTRING, 0x3A29)
	PR_STREET_ADDRESS_W          = propTag(PT_UNICODE, 0x3A29)
	PR_STREET_ADDRESS_A          = propTag(PT_STRING8, 0x3A29)
	PR_BUSINESS_ADDRESS_STREET   = PR_STREET_ADDRESS
	PR_BUSINESS_ADDRESS_STREET_W = PR_STREET_ADDRESS_W
	PR_BUSINESS_ADDRESS_STREET_A = PR_STREET_ADDRESS_A

	PR_POSTAL_CODE                    = propTag(PT_TSTRING, 0x3A2A)
	PR_POSTAL_CODE_W                  = propTag(PT_UNICODE, 0x3A2A)
	PR_POSTAL_CODE_A                  = propTag(PT_STRING8, 0x3A2A)
	PR_BUSINESS_ADDRESS_POSTAL_CODE   = PR_POSTAL_CODE
	PR_BUSINESS_ADDRESS_POSTAL_CODE_W = PR_POSTAL_CODE_W
	PR_BUSINESS_ADDRESS_POSTAL_CODE_A = PR_POSTAL_CODE_A

	PR_POST_OFFICE_BOX                    = propTag(PT_TSTRING, 0x3A2B)
	PR_POST_OFFICE_BOX_W                  = propTag(PT_UNICODE, 0x3A2B)
	PR_POST_OFFICE_BOX_A                  = propTag(PT_STRING8, 0x3A2B)
	PR_BUSINESS_ADDRESS_POST_OFFICE_BOX   = PR_POST_OFFICE_BOX
	PR_BUSINESS_ADDRESS_POST_OFFICE_BOX_W = PR_POST_OFFICE_BOX_W
	PR_BUSINESS_ADDRESS_POST_OFFICE_BOX_A = PR_POST_OFFICE_BOX_A

	PR_TELEX_NUMBER                 = propTag(PT_TSTRING, 0x3A2C)
	PR_TELEX_NUMBER_W               = propTag(PT_UNICODE, 0x3A2C)
	PR_TELEX_NUMBER_A               = propTag(PT_STRING8, 0x3A2C)
	PR_ISDN_NUMBER                  = propTag(PT_TSTRING, 0x3A2D)
	PR_ISDN_NUMBER_W                = propTag(PT_UNICODE, 0x3A2D)
	PR_ISDN_NUMBER_A                = propTag(PT_STRING8, 0x3A2D)
	PR_ASSISTANT_TELEPHONE_NUMBER   = propTag(PT_TSTRING, 0x3A2E)
	PR_ASSISTANT_TELEPHONE_NUMBER_W = propTag(PT_UNICODE, 0x3A2E)
	PR_ASSISTANT_TELEPHONE_NUMBER_A = propTag(PT_STRING8, 0x3A2E)
	PR_HOME2_TELEPHONE_NUMBER       = propTag(PT_TSTRING, 0x3A2F)
	PR_HOME2_TELEPHONE_NUMBER_W     = propTag(PT_UNICODE, 0x3A2F)
	PR_HOME2_TELEPHONE_NUMBER_A     = propTag(PT_STRING8, 0x3A2F)
	PR_ASSISTANT                    = propTag(PT_TSTRING, 0x3A30)
	PR_ASSISTANT_W                  = propTag(PT_UNICODE, 0x3A30)
	PR_ASSISTANT_A                  = propTag(PT_STRING8, 0x3A30)
	PR_SEND_RICH_INFO               = propTag(PT_BOOLEAN, 0x3A40)

	PR_WEDDING_ANNIVERSARY = propTag(PT_SYSTIME, 0x3A41)
	PR_BIRTHDAY            = propTag(PT_SYSTIME, 0x3A42)

	PR_HOBBIES   = propTag(PT_TSTRING, 0x3A43)
	PR_HOBBIES_W = propTag(PT_UNICODE, 0x3A43)
	PR_HOBBIES_A = propTag(PT_STRING8, 0x3A43)

	PR_MIDDLE_NAME   = propTag(PT_TSTRING, 0x3A44)
	PR_MIDDLE_NAME_W = propTag(PT_UNICODE, 0x3A44)
	PR_MIDDLE_NAME_A = propTag(PT_STRING8, 0x3A44)

	PR_DISPLAY_NAME_PREFIX   = propTag(PT_TSTRING, 0x3A45)
	PR_DISPLAY_NAME_PREFIX_W = propTag(PT_UNICODE, 0x3A45)
	PR_DISPLAY_NAME_PREFIX_A = propTag(PT_STRING8, 0x3A45)

	PR_PROFESSION   = propTag(PT_TSTRING, 0x3A46)
	PR_PROFESSION_W = propTag(PT_UNICODE, 0x3A46)
	PR_PROFESSION_A = propTag(PT_STRING8, 0x3A46)

	PR_PREFERRED_BY_NAME   = propTag(PT_TSTRING, 0x3A47)
	PR_PREFERRED_BY_NAME_W = propTag(PT_UNICODE, 0x3A47)
	PR_PREFERRED_BY_NAME_A = propTag(PT_STRING8, 0x3A47)

	PR_SPOUSE_NAME   = propTag(PT_TSTRING, 0x3A48)
	PR_SPOUSE_NAME_W = propTag(PT_UNICODE, 0x3A48)
	PR_SPOUSE_NAME_A = propTag(PT_STRING8, 0x3A48)

	PR_COMPUTER_NETWORK_NAME   = propTag(PT_TSTRING, 0x3A49)
	PR_COMPUTER_NETWORK_NAME_W = propTag(PT_UNICODE, 0x3A49)
	PR_COMPUTER_NETWORK_NAME_A = propTag(PT_STRING8, 0x3A49)

	PR_CUSTOMER_ID   = propTag(PT_TSTRING, 0x3A4A)
	PR_CUSTOMER_ID_W = propTag(PT_UNICODE, 0x3A4A)
	PR_CUSTOMER_ID_A = propTag(PT_STRING8, 0x3A4A)

	PR_TTYTDD_PHONE_NUMBER   = propTag(PT_TSTRING, 0x3A4B)
	PR_TTYTDD_PHONE_NUMBER_W = propTag(PT_UNICODE, 0x3A4B)
	PR_TTYTDD_PHONE_NUMBER_A = propTag(PT_STRING8, 0x3A4B)

	PR_FTP_SITE   = propTag(PT_TSTRING, 0x3A4C)
	PR_FTP_SITE_W = propTag(PT_UNICODE, 0x3A4C)
	PR_FTP_SITE_A = propTag(PT_STRING8, 0x3A4C)

	PR_GENDER = propTag(PT_SHORT, 0x3A4D)

	PR_MANAGER_NAME   = propTag(PT_TSTRING, 0x3A4E)
	PR_MANAGER_NAME_W = propTag(PT_UNICODE, 0x3A4E)
	PR_MANAGER_NAME_A = propTag(PT_STRING8, 0x3A4E)

	PR_NICKNAME   = propTag(PT_TSTRING, 0x3A4F)
	PR_NICKNAME_W = propTag(PT_UNICODE, 0x3A4F)
	PR_NICKNAME_A = propTag(PT_STRING8, 0x3A4F)

	PR_PERSONAL_HOME_PAGE   = propTag(PT_TSTRING, 0x3A50)
	PR_PERSONAL_HOME_PAGE_W = propTag(PT_UNICODE, 0x3A50)
	PR_PERSONAL_HOME_PAGE_A = propTag(PT_STRING8, 0x3A50)

	PR_BUSINESS_HOME_PAGE   = propTag(PT_TSTRING, 0x3A51)
	PR_BUSINESS_HOME_PAGE_W = propTag(PT_UNICODE, 0x3A51)
	PR_BUSINESS_HOME_PAGE_A = propTag(PT_STRING8, 0x3A51)

	PR_CONTACT_VERSION  = propTag(PT_CLSID, 0x3A52)
	PR_CONTACT_ENTRYIDS = propTag(PT_MV_BINARY, 0x3A53)

	PR_CONTACT_ADDRTYPES   = propTag(PT_MV_TSTRING, 0x3A54)
	PR_CONTACT_ADDRTYPES_W = propTag(PT_MV_UNICODE, 0x3A54)
	PR_CONTACT_ADDRTYPES_A = propTag(PT_MV_STRING8, 0x3A54)

	PR_CONTACT_DEFAULT_ADDRESS_INDEX = propTag(PT_LONG, 0x3A55)

	PR_CONTACT_EMAIL_ADDRESSES   = propTag(PT_MV_TSTRING, 0x3A56)
	PR_CONTACT_EMAIL_ADDRESSES_W = propTag(PT_MV_UNICODE, 0x3A56)
	PR_CONTACT_EMAIL_ADDRESSES_A = propTag(PT_MV_STRING8, 0x3A56)

	PR_COMPANY_MAIN_PHONE_NUMBER   = propTag(PT_TSTRING, 0x3A57)
	PR_COMPANY_MAIN_PHONE_NUMBER_W = propTag(PT_UNICODE, 0x3A57)
	PR_COMPANY_MAIN_PHONE_NUMBER_A = propTag(PT_STRING8, 0x3A57)

	PR_CHILDRENS_NAMES   = propTag(PT_MV_TSTRING, 0x3A58)
	PR_CHILDRENS_NAMES_W = propTag(PT_MV_UNICODE, 0x3A58)
	PR_CHILDRENS_NAMES_A = propTag(PT_MV_STRING8, 0x3A58)

	PR_HOME_ADDRESS_CITY   = propTag(PT_TSTRING, 0x3A59)
	PR_HOME_ADDRESS_CITY_W = propTag(PT_UNICODE, 0x3A59)
	PR_HOME_ADDRESS_CITY_A = propTag(PT_STRING8, 0x3A59)

	PR_HOME_ADDRESS_COUNTRY   = propTag(PT_TSTRING, 0x3A5A)
	PR_HOME_ADDRESS_COUNTRY_W = propTag(PT_UNICODE, 0x3A5A)
	PR_HOME_ADDRESS_COUNTRY_A = propTag(PT_STRING8, 0x3A5A)

	PR_HOME_ADDRESS_POSTAL_CODE   = propTag(PT_TSTRING, 0x3A5B)
	PR_HOME_ADDRESS_POSTAL_CODE_W = propTag(PT_UNICODE, 0x3A5B)
	PR_HOME_ADDRESS_POSTAL_CODE_A = propTag(PT_STRING8, 0x3A5B)

	PR_HOME_ADDRESS_STATE_OR_PROVINCE   = propTag(PT_TSTRING, 0x3A5C)
	PR_HOME_ADDRESS_STATE_OR_PROVINCE_W = propTag(PT_UNICODE, 0x3A5C)
	PR_HOME_ADDRESS_STATE_OR_PROVINCE_A = propTag(PT_STRING8, 0x3A5C)

	PR_HOME_ADDRESS_STREET   = propTag(PT_TSTRING, 0x3A5D)
	PR_HOME_ADDRESS_STREET_W = propTag(PT_UNICODE, 0x3A5D)
	PR_HOME_ADDRESS_STREET_A = propTag(PT_STRING8, 0x3A5D)

	PR_HOME_ADDRESS_POST_OFFICE_BOX   = propTag(PT_TSTRING, 0x3A5E)
	PR_HOME_ADDRESS_POST_OFFICE_BOX_W = propTag(PT_UNICODE, 0x3A5E)
	PR_HOME_ADDRESS_POST_OFFICE_BOX_A = propTag(PT_STRING8, 0x3A5E)

	PR_OTHER_ADDRESS_CITY   = propTag(PT_TSTRING, 0x3A5F)
	PR_OTHER_ADDRESS_CITY_W = propTag(PT_UNICODE, 0x3A5F)
	PR_OTHER_ADDRESS_CITY_A = propTag(PT_STRING8, 0x3A5F)

	PR_OTHER_ADDRESS_COUNTRY   = propTag(PT_TSTRING, 0x3A60)
	PR_OTHER_ADDRESS_COUNTRY_W = propTag(PT_UNICODE, 0x3A60)
	PR_OTHER_ADDRESS_COUNTRY_A = propTag(PT_STRING8, 0x3A60)

	PR_OTHER_ADDRESS_POSTAL_CODE   = propTag(PT_TSTRING, 0x3A61)
	PR_OTHER_ADDRESS_POSTAL_CODE_W = propTag(PT_UNICODE, 0x3A61)
	PR_OTHER_ADDRESS_POSTAL_CODE_A = propTag(PT_STRING8, 0x3A61)

	PR_OTHER_ADDRESS_STATE_OR_PROVINCE   = propTag(PT_TSTRING, 0x3A62)
	PR_OTHER_ADDRESS_STATE_OR_PROVINCE_W = propTag(PT_UNICODE, 0x3A62)
	PR_OTHER_ADDRESS_STATE_OR_PROVINCE_A = propTag(PT_STRING8, 0x3A62)

	PR_OTHER_ADDRESS_STREET   = propTag(PT_TSTRING, 0x3A63)
	PR_OTHER_ADDRESS_STREET_W = propTag(PT_UNICODE, 0x3A63)
	PR_OTHER_ADDRESS_STREET_A = propTag(PT_STRING8, 0x3A63)

	PR_OTHER_ADDRESS_POST_OFFICE_BOX   = propTag(PT_TSTRING, 0x3A64)
	PR_OTHER_ADDRESS_POST_OFFICE_BOX_W = propTag(PT_UNICODE, 0x3A64)
	PR_OTHER_ADDRESS_POST_OFFICE_BOX_A = propTag(PT_STRING8, 0x3A64)
)
